### ISSUE TITLE
@cjsrinivas's tracking for GitHub Flow

### ISSUE THREAD

**Issue by cjsrinivas** [githubteacher/developers-jun-2016-emea#84]
- [ ] create a branch
- [ ] add commits
- [ ] open a pull request
- [ ] code review (conversation)
- [ ] add additional commits
- [ ] merge when 👍 , 🚢 , :shipit:
