### ISSUE TITLE
Sams tracking for GitHub Flow

### ISSUE THREAD

**Issue by SamSneesby** [githubteacher/developers-jun-2016-emea#95]
- [ ] a branch
  - [ ] add commits
  - [ ] open a pull request
  - [ ] code review (conversation)
  - [ ] add additional commits
  - [ ] merge when 👍 , 🚢 , :shipit:
